# Generated by Django 4.2.2 on 2023-06-26 09:21

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Day_Hate",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("rec_date", models.DateField()),
                ("user_id", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Device",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("user_id", models.IntegerField()),
                ("rp_serial", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="Time_Hate",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("rec_datetime", models.DateTimeField()),
                ("user_id", models.IntegerField()),
                ("fg_none", models.FloatField()),
                ("fg_other_hate", models.FloatField()),
                ("fg_man", models.FloatField()),
                ("fg_normal_bad_comments", models.FloatField()),
                ("fg_sexual_minority", models.FloatField()),
                ("fg_woman_or_family", models.FloatField()),
                ("fg_age", models.FloatField()),
                ("fg_race_or_nationality", models.FloatField()),
                ("fg_religion", models.FloatField()),
                ("fg_region", models.FloatField()),
                ("speech", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
